language: node_js
node_js:
- '4.4'

before_install:
- npm install -g npm

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run es6-coverage

cache:
  directories:
    - node_modules
